### ISSUE TITLE
getting error while installing npm  some 

### ISSUE THREAD

**Issue by aslamsk** [jgudo/ecommerce-react#18] opened 2020-10-24 16:33 UTC
getting error while installing npm  some 
![Screenshot (30)](https://user-images.githubusercontent.com/54580538/97087036-f35e5980-15db-11eb-940e-686e1f82f91f.png)

**Comment by jgudo** [comment] 2020-10-25 00:17
Have you tried deleting the package-lock.json and node_modules then run npm install again?

**Comment by aslamsk** [comment] 2020-10-25 10:16
Yah I tried  but till getting

**Comment by jgudo** [comment] 2020-10-26 10:23
Even after cleaning the npm cache? ```npm cache clean --force```

**Comment by aslamsk** [comment] 2020-10-26 15:00
This process also done but not worked till getting same to same error

**Comment by jgudo** [comment] 2020-10-26 15:13
What version of npm are you using? 
Try again deleting node_modules + package-lock.json + running ```npm cache clean --force```. If the problem still exists, try reinstalling/update node/npm. I'm going to close this since I can't reproduce the problem and it seems that problem is in your end.

**Closed by jgudo** 2020-10-26 15:13 UTC
